Repository DITP-pilotage/pilote-2, pull requests merged in 2023-01, with the labels that each got.

#69 fix: corrige l'affichage d'un chantier à la maille nationale avec les vraies données (107)
  src/pages/chantier/[id].tsx
  src/pages/index.tsx
  src/server/domain/chantier/ChantierInfoRepository.interface.ts
  src/server/infrastructure/chantier/ChantierInfoRandomRepository.ts
  src/server/infrastructure/chantier/ChantierInfoSQLRepository.integration.test.ts
  src/server/infrastructure/chantier/ChantierInfoSQLRepository.ts
Labels: bug

#81 chore: suppression colonne perimetre_id de la table public.chantier (124)
  data/pilote_data_jobs/transformations/chantier/brute_vers_public.sql
  prisma/migrations/20230109145755_suppression_de_la_colonne_id_perimetre_de_la_table_chantier/migration.sql
  prisma/schema.prisma
  src/server/infrastructure/chantier/ChantierSQLRepository.ts
Labels: data

#79 feat: ajout des noms des porteurs DAC dans la table public.chantier (…
  data/migrations/model.py
  data/migrations/versions/202301091531_ajout_du_porteur_directeur_dans_la_.py
  data/pilote_data_jobs/scripts/fill_tables_raw_data.sh
  data/pilote_data_jobs/transformations/chantier/brute_vers_public.sql
Labels: data

#80 feat: branchement des donnees des indicateurs maille nationale sur la page chantier (52)
  src/client/components/PageChantier/PageChantier.interface.ts
  src/client/components/PageChantier/PageChantier.tsx
  src/fixtures/ChantierFixture.ts
  src/pages/chantier/[id].tsx
  src/server/domain/chantier/Chantier.interface.ts
  src/server/domain/indicateur/Indicateur.interface.ts
  src/server/domain/indicateur/IndicateurRepository.interface.ts
  src/server/infrastructure/Dependencies.ts
  src/server/infrastructure/chantier/ChantierRandomRepository.unit.test.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.ts
  src/server/infrastructure/indicateur/IndicateurRandomRepository.ts
  src/server/infrastructure/indicateur/IndicateurSQLRepository.integration.test.ts
  src/server/infrastructure/indicateur/IndicateurSQLRepository.ts
  src/server/infrastructure/test/indicateur/IndicateurRowBuilder.ts
Labels: enhancement, front, back

#87 fix: renommage colonne directeurs_projet et passage de string à liste (135)
  data/pilote_data_jobs/transformations/chantier/brute_vers_public.sql
  prisma/migrations/20230111103103_renommage_colonne_directeurs_projet_et_passage_en_liste/migration.sql
  prisma/schema.prisma
  src/fixtures/ChantierFixture.ts
  src/server/domain/chantier/Chantier.interface.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.ts
Labels: data

#86 refactor: envoie une erreur explicite si maille inconnue (52)
  src/server/domain/chantier/ChantierRepository.interface.ts
  src/server/infrastructure/chantier/ChantierRandomRepository.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.integration.test.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.ts
  src/server/infrastructure/indicateur/IndicateurSQLRepository.integration.test.ts
  src/server/infrastructure/test/integrationTestSetup.ts
  src/server/infrastructure/test/rowBuilder/ChantierRowBuilder.ts
  src/server/infrastructure/test/rowBuilder/IndicateurRowBuilder.ts
Labels: enhancement, back

#95 feat: affichage des données de météo nationale (138)
  package.json
  src/client/components/PageChantier/AvancementChantier/AvancementChantier.tsx
  src/client/components/PageChantiers/ListeChantiers/ListeChantiers.tsx
  src/client/utils/cartographie/préparerDonnéesCartographie.ts
  src/client/utils/chantier/donnéesTerritoires/donnéesTerritoires.ts
  src/fixtures/ChantierFixture.ts
  src/server/domain/chantier/Chantier.interface.ts
  src/server/domain/chantier/Météo.interface.ts
  src/server/domain/chantier/Météo.interface.unit.test.ts
  src/server/infrastructure/chantier/ChantierRandomRepository.unit.test.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.integration.test.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.ts
  src/server/infrastructure/test/rowBuilder/ChantierRowBuilder.ts
Labels: enhancement, back

#114 feat: expose les données porteurs des chantiers (101)
  prisma/schema.prisma
  src/client/components/PageChantier/PageChantier.tsx
  src/client/components/PageChantier/Responsables/Responsables.interface.ts
  src/client/components/PageChantier/Responsables/Responsables.tsx
  src/client/components/PageChantier/Responsables/ResponsablesLigne/ResponsablesLigne.interface.ts
  src/client/components/PageChantier/Responsables/ResponsablesLigne/ResponsablesLigne.tsx
  src/fixtures/ChantierFixture.ts
  src/pages/index.tsx
  src/server/domain/chantier/Chantier.interface.ts
  src/server/infrastructure/chantier/ChantierSQLParser.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.integration.test.ts
  src/server/infrastructure/chantier/ChantierSQLRepository.ts
  src/server/infrastructure/test/rowBuilder/ChantierRowBuilder.ts
Labels: back
